# Generated by Django 4.0.1 on 2024-06-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_restaurant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
    ]
